# markdownlint-cli npm package
# https://www.npmjs.com/package/markdownlint-cli
# print
# markdownlint '**/*.md' --ignore node_modules
# fix basic errors
# markdownlint '**/*.md' --ignore node_modules --fix

# MD001 - Heading levels should only increment by one level at a time
MD001: false

# MD002 - First heading should be a top level heading
MD002: false

# MD003 - Heading style
MD003: false

# MD004 - Unordered list style
MD004: false

# MD005 - Inconsistent indentation for list items at the same level
MD005: false

# MD006 - Consider starting bulleted lists at the beginning of the line
MD006: false

# MD007 - Unordered list indentation
MD007: false

# MD009 - Trailing spaces
MD009: false

# MD010 - Hard tabs
MD010: false

# MD013 - Line length
MD013: false

# MD014 - Dollar signs used before commands without showing output
MD014: false

# MD024 - Multiple headings with the same content
MD024: false

# MD025 - Multiple top level headings in the same document
MD025: false

# MD026 - Trailing punctuation in heading
MD026: false

# MD028 - Blank line inside blockquote
MD028: false

# MD029 - Ordered list item prefix
MD029: false

# MD030 - Spaces after list markers
MD030: false

# MD033 - Inline HTML
MD033: false

# MD036 - Emphasis used instead of a heading
MD036: false

# MD037 - Spaces inside emphasis markers
MD037: false

# MD040 - Fenced code blocks should have a language specified
MD040: false

# MD041 - First line in file should be a top level heading
MD041: false

# MD046 - Code block style
MD046: false

# MD047 - Files should end with a single newline character
MD047: false
