FROM lucee/lucee:7.1.0.169-SNAPSHOT

COPY lucee-config.json /opt/lucee/server/lucee-server/context/.CFConfig.json
COPY extensions/mcp-server-extension-1.0.1.1-BETA.lex /opt/lucee/server/lucee-server/context/deploy/
