name: Generate Recipes Index

on:
  push:
    branches:
      - "**"
    paths:
      - "docs/recipes/**"
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install fs-extra

      - name: Generate index
        run: |
          node .github/scripts/generate-index-recipes.js

      - name: Commit and push changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "Lucee Docs GitHub Action"
            git add docs/recipes/index.json docs/recipes/README.md
            git commit -m "Update recipes index and README"
            git push origin $BRANCH_NAME
          else
            echo "No changes found to commit"
          fi
