# This is a basic workflow to help you get started with Actions

name: Test Build Lucee docs using Script Runner

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: lucee-script-runner-m2-cache
      - name: Cache Lucee files
        uses: actions/cache@v4
        with:
          path: _actions/lucee/script-runner/main/lucee-download-cache
          key: lucee-downloads-${{ env.luceeVersion }}
          restore-keys: |
            lucee-downloads
      # Runs a single command using the runners shell
      - name: Build Lucee Docs
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}
          execute: /build-all.cfm
          # luceeVersion: 6.0.0.95-SNAPSHOT
          luceeVersion: 5.3.10.97
